### ISSUE TITLE
Fix scrollable sidebar

### ISSUE THREAD

**Issue by oski646** [MilyMilo/educat#27]
Podczas scrollowania treści "głównej" scrolluje się również sidebar co nie powinno mieć miejsca.
<img width="1673" alt="Screenshot 2020-03-11 at 00 37 33" src="https://user-images.githubusercontent.com/28627427/76368505-c8671400-6330-11ea-9248-25f54af50eac.png">

Na załączonym obrazku wcina **Dashboard** pod navbara.

**Comment by MilyMilo** [comment]
Sidebar powinien mieć najprawdopodobniej `position: absolute` albo `fixed`, jeżeli teraz nie ma.
